# SPDX-FileCopyrightText: 2023 Nick Korotysh <nick.korotysh@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: CI - macOS

on: [pull_request, push]

permissions:
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Build
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Install dependencies
        run: |
          brew update > /dev/null
          brew install cmake ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.7.*"
          archives: qtbase qtsvg

      - name: Build application
        run: |
          cmake \
            -B build \
            -G Ninja \
            -D CMAKE_OSX_DEPLOYMENT_TARGET=12.0 \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

      - name: Prepare build artifacts
        run: |
          pushd build
          macdeployqt DigitalClockNext.app -dmg -codesign=-
          popd
          mkdir upload
          mv build/DigitalClockNext.dmg upload/digital_clock_next-macos.dmg

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DigitalClockNext macOS Nightly
          path: upload
