name: CI - Windows

on: [pull_request, push]

permissions:
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Build
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Setup devcmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install build tools
        run: |
          choco install ninja

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: "6.5.*"
          archives: qtbase qtsvg

      - name: Build application
        run: |
          cmake `
            -B build `
            -G Ninja `
            -D CMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

      - name: Prepare build artifacts
        run: |
          mkdir upload
          mkdir DigitalClockNext
          copy build/DigitalClockNext.exe DigitalClockNext
          cd DigitalClockNext
          New-Item -Name portable.txt -ItemType File
          attrib +h portable.txt
          windeployqt --libdir . --plugindir "plugins" --no-compiler-runtime --no-system-d3d-compiler --no-opengl-sw --no-translations DigitalClockNext.exe
          cd ..
          7z a upload/digital_clock_next-win64.zip DigitalClockNext

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: DigitalClockNext Windows Nightly
          path: upload
