# SPDX-FileCopyrightText: 2023 Nick Korotysh <nick.korotysh@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: CI - Windows

on: [pull_request, push]

permissions:
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.head_ref != '' }}

jobs:
  ci:
    name: Build
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          submodules: recursive

      - name: Setup devcmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install build tools
        run: |
          "C:\Program Files (x86)\WiX Toolset v3.14\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.7.*"
          archives: qtbase qtsvg

      - name: Build application
        run: |
          cmake `
            -B build `
            -G Ninja `
            -D CMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure

      - name: Prepare build artifacts
        run: |
          cmake --build build --target win_installer
          mkdir upload
          move build\dist\msi\digital_clock_next-x64.msi upload
          move build\installer_files DigitalClockNext
          New-Item -ItemType File -Path DigitalClockNext -Name portable.txt
          attrib +h DigitalClockNext\portable.txt
          7z a upload\digital_clock_next-win64.zip DigitalClockNext

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DigitalClockNext Windows Nightly
          path: upload
